# -*- coding: utf-8 -*-
"""Helper functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qMvmsEyHyfWUz5mSFdLtTsTmgsRb9iLk
"""
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
def view_random_image(target_dir, target_class):
  # saving the target folder name in a variable
  target_folder=target_dir+"/"+target_class

  #Selecting a random image
  random_img=random.sample(os.listdir(target_folder),1)

  #Displaying the random image
  img=mpimage.imread(target_folder+"/" +random_img[0])
  '''
  Here random_img is a list but we need a string in the function hence with
  random_img[0] the list is converted to string on 0 axis'''
  plt.imshow(img)
  plt.title(target_class)
  plt.axis("off");

  print(f"image shape is:{img.shape}")
  return img

#Creating a helper function to plot the loss curves separately
def plot_loss_curve(history):
  training_loss=history.history["loss"]
  val_loss=history.history["val_loss"]
  training_accuracy=history.history["accuracy"]
  val_accuracy=history.history["val_accuracy"]
  epochs=range(len(history.history["loss"]))

  #Loss the loss
  plt.plot(epochs,training_loss, label="Training_loss")
  plt.plot(epochs, val_loss, label="Validation_loss")
  plt.title("Loss")
  plt.xlabel("Epochs")
  plt.legend()

  #Plot accuracy
  plt.figure()
  plt.plot(epochs, training_accuracy, label="Training Accuracy")
  plt.plot(epochs, val_accuracy, label="Validation_Accuracy")
  plt.title("Accuracy")
  plt.xlabel("Epochs")
  plt.legend();

# helper function to load the image and resize it
def load_prep_img (filename, img_shape=224):
  '''
  Read the image from a file name, coverts into tensors and reshape it into 
  (img_shape,img_shape,colour channel)'''
  #Read the target file(image)
  img=tf.io.read_file(filename)

  #Decode the image to tensor with 3 colour channel
  img=tf.image.decode_image(img, channels=3) 
  #tf.image.decode_image(img, channels=3)

  #Resize the image to (224,224) as our model was trained as (224,224,3)
  img=tf.image.resize(img,size=[img_shape,img_shape])

  #Rescale the image
  img=img/255

  return img

def prep_and_plot(filename, model,class_name):
  '''
  it takes input of filename (i.e new unseen image), predicts with model and 
  display the result'''
  #Read the file
  img=tf.io.read_file(filename)

  #Decode the file
  img=tf.image.decode_image(img)

  #Resize and normalize the image
  img=tf.image.resize(img,size=(224,224))/255

  #loads the image
  #img=load_prep_img(filename)# we don't need "load_prep_img" function as it is brought under this function

  #expand one dimention of the read file as the new image file as its shape is
  #(ht,wt,color channel) but model is trained on (batch size, ht, wt,colour channel). 
  #So we need to expand one dimension of the new image so that we can predict on the image

  pred=model.predict(tf.expand_dims(img,axis=0))

  #Get the predicted class
  pred_class=class_names[int(tf.round(pred))]

  #Plot the image
  plt.imshow(img)
  plt.title(f"prediction {pred_class}")
  plt.axis(False);

#Walk through the 'directory name', "filenames" and 'directory path
def walk_through(directory):
  '''Walk through the 'dirname', "filenames" and 'directory path'''
  import os
  for dirpath,dirname, filename in os.walk(directory):
    print(f"There are {len(dirnames)} directories and {len(filepath)} images in '{dirpath}'.")
    
    
  # Create the confustion matrix
  cm = confusion_matrix(y_true, y_pred)
  cm_norm = cm.astype("float") / cm.sum(axis=1)[:, np.newaxis] # normalize it
  n_classes = cm.shape[0] # find the number of classes we're dealing with

  # Plot the figure and make it pretty
  fig, ax = plt.subplots(figsize=figsize)
  cax = ax.matshow(cm, cmap=plt.cm.Blues) # colors will represent how 'correct' a class is, darker == better
  fig.colorbar(cax)

  # Are there a list of classes?
  if classes:
    labels = classes
  else:
    labels = np.arange(cm.shape[0])
  
  # Label the axes
  ax.set(title="Confusion Matrix",
         xlabel="Predicted label",
         ylabel="True label",
         xticks=np.arange(n_classes), # create enough axis slots for each class
         yticks=np.arange(n_classes), 
         xticklabels=labels, # axes will labeled with class names (if they exist) or ints
         yticklabels=labels)
  
  # Make x-axis labels appear on bottom
  ax.xaxis.set_label_position("bottom")
  ax.xaxis.tick_bottom()

  # Set the threshold for different colors
  threshold = (cm.max() + cm.min()) / 2.

  # Plot the text on each cell
  for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
    if norm:
      plt.text(j, i, f"{cm[i, j]} ({cm_norm[i, j]*100:.1f}%)",
              horizontalalignment="center",
              color="white" if cm[i, j] > threshold else "black",
              size=text_size)
    else:
      plt.text(j, i, f"{cm[i, j]}",
              horizontalalignment="center",
              color="white" if cm[i, j] > threshold else "black",
              size=text_size)

  # Save the figure to the current working directory
  if savefig:
    fig.savefig("confusion_matrix.png")